name: Build and Deploy Frontend

on:
  push:
    branches:
      - "main"
    paths:   
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install
        working-directory: frontend/
      - name: Build
        run: npm run build
        working-directory: frontend/
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: frontend/build # The folder the action should deploy.
